apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      securityContext:
        runAsNonRoot: true          # CKV_K8S_23, CKV_K8S_40
        runAsUser: 1000
        seccompProfile:             # CKV_K8S_31
          type: RuntimeDefault
      containers:
        - name: log-output
          image: quangcuonghuynh/log-output:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:                # CKV_K8S_12, CKV_K8S_13
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          securityContext:          # CKV_K8S_29, CKV_K8S_37, CKV_K8S_22
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:            # CKV_K8S_7
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:           # CKV_K8S_9
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      automountServiceAccountToken: false  # CKV_K8S_38
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      